services:
    mariadb:
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_ROOT_PASSWORD=root_password
        healthcheck:
            interval: 10s
            retries: 5
            test: ['CMD', 'mariadb-admin', 'ping', '-h', 'localhost']
            timeout: 5s
        image: mariadb:latest
        ports:
            - '13306:3306'
    mysql:
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_ROOT_PASSWORD=root_password
        healthcheck:
            interval: 10s
            retries: 5
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 5s
        image: mysql:latest
        ports:
            - '23306:3306'
    postgres:
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_PORT=15432
            - POSTGRES_DB=test_db
            - POSTGRES_USER=test_user
            - POSTGRES_PASSWORD=test_password
        healthcheck:
            interval: 10s
            retries: 5
            test:
                ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
            timeout: 5s
        image: postgres:alpine
        ports:
            - '15432:5432'
