services:
    mysql:
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_ROOT_PASSWORD=root_password
        image: mysql:latest
        ports:
            - '13306:3306'
    postgres:
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_PORT=15432
            - POSTGRES_DB=test_db
            - POSTGRES_USER=test_user
            - POSTGRES_PASSWORD=test_password
        image: postgres:alpine
        ports:
            - '15432:5432'
